---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: kubernetes
spec:
  # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
  version: "v1.29.2"
  serviceAccountName: system-upgrade
  secrets:
    - name: talos
      path: /var/run/secrets/talos.dev
      ignoreUpdates: true
  concurrency: 1
  exclusive: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  prepare: &prepare
    image: "registry.k8s.io/kubectl:v1.29.3@sha256:231402b1cbb0b1598f5eebe1729108f80b68ad22891329f17af7773f462afcef"
    args: # if Ceph is completely healthy, surely k8s is healthy, right?
      - "wait"
      - "--timeout=300s"
      - |
        --for=jsonpath=.status.ceph.health=HEALTH_OK
      - "cephcluster"
      - "--all"
      - "--all-namespaces"
  upgrade:
    image: "ghcr.io/siderolabs/talosctl:${TALOS_VERSION}"
    envs:
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    args:
      - "--nodes=$(NODE_IP)"
      - "upgrade-k8s"
      - "--to=$(SYSTEM_UPGRADE_PLAN_LATEST_VERSION)"
