---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: talos
spec:
  version: &v "${TALOS_VERSION}"
  serviceAccountName: system-upgrade
  secrets:
    - name: talos
      path: /var/run/secrets/talos.dev
      ignoreUpdates: true
  concurrency: 1
  exclusive: true
  nodeSelector:
    matchExpressions:
      - key: feature.node.kubernetes.io/system-os_release.ID
        operator: In
        values: ["talos"]
      - key: feature.node.kubernetes.io/system-os_release.VERSION_ID
        operator: NotIn
        values: [*v]
  prepare: &prepare
    image: "registry.k8s.io/kubectl:v1.29.3@sha256:231402b1cbb0b1598f5eebe1729108f80b68ad22891329f17af7773f462afcef"
    args: # if Ceph is completely healthy, surely k8s is healthy, right?
      - "wait"
      - "--timeout=3600s"
      - |
        --for=jsonpath=.status.ceph.health=HEALTH_OK
      - "cephcluster"
      - "--all"
      - "--all-namespaces"
    #image: "ghcr.io/siderolabs/talosctl:${TALOS_VERSION}"
    #envs:
    #  - name: NODE_IP
    #    valueFrom:
    #      fieldRef:
    #        fieldPath: status.hostIP
    #args:
    #  - "--nodes=$(NODE_IP)"
    #  - "health"
    #  - "--server=false"
    #    kubectl wait --for=condition=Ready --timeout=1h node/charlotte
  upgrade:
    image: "ghcr.io/siderolabs/talosctl:${TALOS_VERSION}"
    envs:
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    args:
      - "--nodes=$(NODE_IP)"
      - "upgrade"
      - "--image=${TALOS_IMAGE}:$(SYSTEM_UPGRADE_PLAN_LATEST_VERSION)"
      - "--preserve=true"
      - "--wait=false"
